#!/usr/bin/env sh
# Install or upgrade artifact-driven-dev skills into a target project.
# Usage: ./install.sh [target-dir]
# Defaults to the current directory if no target is given.
# Safe to re-run — skills are overwritten, migrations are applied once.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET="${1:-.}"
SKILLS_DIR="$SCRIPT_DIR/skills"
MIGRATIONS_DIR="$SCRIPT_DIR/migrations"
CLAUDE_SKILLS="$TARGET/.claude/skills"
APPLIED_FILE="$TARGET/.ardd-applied"
VERSION_FILE="$TARGET/.project/ardd-version.md"
CONSTITUTION_DATA_DIR="$CLAUDE_SKILLS/ardd-constitution-data"
ARTIFACT_TEMPLATES_DIR="$CLAUDE_SKILLS/ardd-artifact-templates"

if [ ! -d "$TARGET" ]; then
  echo "Error: target directory '$TARGET' does not exist." >&2
  exit 1
fi

# --- Skills ---
echo "Installing artifact-driven-dev skills into $TARGET ..."

installed_skill_names=""
for skill_dir in "$SKILLS_DIR"/*/; do
  skill_name="$(basename "$skill_dir")"
  dest="$CLAUDE_SKILLS/$skill_name"
  mkdir -p "$dest"
  cp "$skill_dir/SKILL.md" "$dest/SKILL.md"
  echo "  ✓ $skill_name"
  installed_skill_names="$installed_skill_names $skill_name"
done

# --- Constitution suggestion catalog ---
# Not a skill (no SKILL.md, so it never registers as an invokable command) —
# reference data /ardd-bootstrap and /ardd-codify read at constitution-
# creation time. Lives under .claude/skills/ardd-* so it's covered by the
# same gitignore guidance already given for ardd-* skill directories below.
mkdir -p "$CONSTITUTION_DATA_DIR"
cp "$SCRIPT_DIR/templates/constitution-suggestions.md" "$CONSTITUTION_DATA_DIR/constitution-suggestions.md"
echo "  ✓ ardd-constitution-data/constitution-suggestions.md"

# --- Artifact templates ---
# Not skills either — structure skeletons /ardd-bootstrap, /ardd-refine, and
# /ardd-add-artifact fill in from context when creating/refining an artifact.
# These previously only existed in the ADD source repo, never in a target
# project, so the "look for templates/artifacts/<name>.md in the ADD
# installation" instruction those skills carried was a no-op outside this
# repo; falling back to generic.md silently absorbed the gap. Same fix as
# the constitution catalog above: copy them so the fixed path actually
# resolves in a target project.
mkdir -p "$ARTIFACT_TEMPLATES_DIR"
cp "$SCRIPT_DIR"/templates/artifacts/*.md "$ARTIFACT_TEMPLATES_DIR/"
echo "  ✓ ardd-artifact-templates/ ($(ls "$SCRIPT_DIR"/templates/artifacts/*.md | wc -l | tr -d ' ') templates)"

# --- Migrations ---
if [ -d "$MIGRATIONS_DIR" ]; then
  echo ""
  echo "Applying migrations ..."

  touch "$APPLIED_FILE"
  any_new=0

  for migration in "$MIGRATIONS_DIR"/*.sh; do
    [ -f "$migration" ] || continue
    migration_name="$(basename "$migration")"
    if grep -qxF "$migration_name" "$APPLIED_FILE"; then
      echo "  – $migration_name (already applied)"
    else
      sh "$migration" "$TARGET"
      echo "$migration_name" >> "$APPLIED_FILE"
      echo "  ✓ $migration_name"
      any_new=1
    fi
  done

  if [ "$any_new" -eq 0 ]; then
    echo "  (none pending)"
  fi
fi

# --- Version file ---
# .claude/skills/ is regenerated output (gitignore it); this file is the
# committed, human-readable record of which ARDD version produced it.
COMMIT="$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(date +%Y-%m-%d)"
mkdir -p "$(dirname "$VERSION_FILE")"
cat > "$VERSION_FILE" <<EOF
# ARDD Version

_Source: artifact-driven-dev @ $COMMIT · Installed/updated ${DATE}_

This file is committed so the project's history shows which ARDD skill
version was active at any point. \`.claude/skills/\` is regenerated by
\`install.sh\` from that source commit and should be gitignored, not
committed.
EOF
echo ""
echo "  ✓ .project/ardd-version.md ($COMMIT)"

# --- Gitignore check ---
# Ask git itself whether the skills would show up in `git status` (untracked
# or previously committed) rather than parsing .gitignore text — this is
# what actually determines whether they'd get committed.
if git -C "$TARGET" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
   && ! git -C "$TARGET" check-ignore -q ".claude/skills/ardd-plan/SKILL.md" 2>/dev/null; then

  tracked_other_claude=0   # tracked files directly under .claude/ (e.g. settings.json)
  tracked_other_skills=0   # tracked skills under .claude/skills/ that aren't ours
  tracked_ardd=0           # our own ardd-* skills already committed

  tracked_files="$(git -C "$TARGET" ls-files -- .claude)"
  if [ -n "$tracked_files" ]; then
    old_ifs="$IFS"
    IFS='
'
    for f in $tracked_files; do
      case "$f" in
        .claude/skills/*/*)
          rest="${f#.claude/skills/}"
          skill_name="${rest%%/*}"
          case " $installed_skill_names ardd-constitution-data ardd-artifact-templates " in
            *" $skill_name "*) tracked_ardd=1 ;;
            *) tracked_other_skills=1 ;;
          esac
          ;;
        .claude/skills/*) tracked_other_skills=1 ;;
        *) tracked_other_claude=1 ;;
      esac
    done
    IFS="$old_ifs"
  fi

  echo ""
  echo "Note: .claude/skills/ isn't gitignored in $TARGET — these files are"
  echo "regenerated by install.sh, not project source. Add one of these"
  echo "patterns to .gitignore, depending on what else lives under .claude/:"
  echo ""
  if [ "$tracked_other_skills" -eq 0 ] && [ "$tracked_other_claude" -eq 0 ]; then
    echo "  .claude/                 # nothing else tracked under .claude/ — ignore all of it"
  elif [ "$tracked_other_skills" -eq 1 ]; then
    echo "  .claude/skills/ardd-*/   # non-ARDD skills (or other .claude/ files) are tracked here — ignore only ours"
  else
    echo "  .claude/skills/          # other .claude/ files (e.g. settings.json) are tracked, but no custom skills — ignore all skills"
  fi

  if [ "$tracked_ardd" -eq 1 ]; then
    echo ""
    echo "  ardd-* skill files are already committed here. After updating"
    echo "  .gitignore, untrack them with:"
    echo "    git rm -r --cached .claude/skills/ardd-*"
  fi

  echo ""
  echo "  Commit .project/ardd-version.md instead — it's the lightweight,"
  echo "  human-readable record of which ARDD version produced them."
fi

echo ""
echo "Done. Next steps for a new project:"
echo "  1. Run /ardd-bootstrap in Claude Code to seed your project artifacts."
echo "  2. Run /ardd-analyze to check for cross-artifact issues."
echo "  3. Run /ardd-plan when artifacts are stable."
echo ""
echo "For an existing project, run /ardd-analyze to verify everything looks right."
